name: pull-prices
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get ETH/LDO/SUI prices from CoinGecko
        run: |
          ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          response=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=ethereum,ldo-dao,sui&vs_currencies=usd")
          jq -n --arg ts "$ts" \
            --argjson prices "$response" \
            '{timestamp:$ts, data:[
                {symbol: "ETHUSDT", price: ( $prices.ethereum.usd|tostring )},
                {symbol: "LDOUSDT", price: ( $prices["lido-dao"].usd|tostring )},
                {symbol: "SUIUSDT", price: ( $prices.sui.usd|tostring )}
            ] }' > latest.json

      - name: Commit if changed
        run: |
          git config user.email "bot@example.com"
          git config user.name  "price-bot"
          git add latest.json
          git commit -m "auto: $(date -u)" || echo "no change"
          git push
